packages:
  - '.'
allowBuilds:
  '@tailwindcss/oxide': false
  esbuild: false
  pnpm: set this to true or false
supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
